// ----------------------------------------------------------------------------
// Copyright 2018 Nervana Systems Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// ----------------------------------------------------------------------------

#include "collect_headers.hpp"
#include "compiler.hpp"
#include "file_util.hpp"
#include "util.hpp"

using namespace std;

static string s_header = R"(// Generated by the NGraph CPU backend
#include <cmath>

#include <tbb/flow_graph.h>

#include <Eigen/Dense>

#include "ngraph/runtime/aligned_buffer.hpp"
#include "ngraph/runtime/cpu/cpu_eigen_utils.hpp"
#include "ngraph/runtime/cpu/cpu_kernels.hpp"
#include "ngraph/runtime/kernel/avg_pool.hpp"
#include "ngraph/runtime/kernel/broadcast.hpp"
#include "ngraph/runtime/kernel/concat.hpp"
#include "ngraph/runtime/kernel/convolution.hpp"
#include "ngraph/runtime/kernel/dot.hpp"
#include "ngraph/runtime/kernel/max_pool.hpp"
#include "ngraph/runtime/kernel/not.hpp"
#include "ngraph/runtime/kernel/one_hot.hpp"
#include "ngraph/runtime/kernel/pad.hpp"
#include "ngraph/runtime/kernel/reduce.hpp"
#include "ngraph/runtime/kernel/reduce_window.hpp"
#include "ngraph/runtime/kernel/replace_slice.hpp"
#include "ngraph/runtime/kernel/reverse.hpp"
#include "ngraph/runtime/kernel/select_and_scatter.hpp"
#include "ngraph/runtime/kernel/slice.hpp"
#include "ngraph/runtime/kernel/sum.hpp"
#include "ngraph/util.hpp"


xxxx

yy

xx
)";

static string find_path(const string& path)
{
    string rc;
    iterate_files(path,
                  [&](const string& file, bool is_dir) {
                      if (is_dir)
                      {
                          string dir_name = file_util::get_file_name(file);
                          if (is_version_number(dir_name))
                          {
                              rc = file;
                          }
                      }
                  },
                  true);
    return rc;
}

vector<ResourceInfo> collect_headers()
{
    cout << "collect_header 1" << endl;
    Compiler c;
    c.compile(s_header);

    string cpp0 = find_path("/usr/include/x86_64-linux-gnu/c++/");
    string cpp1 = find_path("/usr/include/c++/");

    vector<ResourceInfo> include_paths;
    // include_paths.push_back({CLANG_BUILTIN_HEADERS_PATH, {}, true});
    // include_paths.push_back({"/usr/include/x86_64-linux-gnu", {"asm", "sys", "bits", "gnu"}});
    // include_paths.push_back({"/usr/include", {"linux", "asm-generic"}});
    // include_paths.push_back({cpp0, {"bits"}});
    // include_paths.push_back({cpp1, {"bits", "ext", "debug", "backward"}});
    // include_paths.push_back({EIGEN_HEADERS_PATH, {}, true});
    // include_paths.push_back({NGRAPH_HEADERS_PATH, {}, true});
    // include_paths.push_back({TBB_HEADERS_PATH, {}, true});

    return include_paths;
}
